name: CustomKeepInventory
version: 1.2
main: me.miguel.keepinventory.Main
api-version: 1.21
authors: [Miguel]

commands:
  kp:
    description: Ativa ou desativa o KeepInventory para o servidor inteiro.
    permission: op
    
