name: Gerar Plugin JAR

on:
  push:
    branches: [ "principal" ] # Aqui está o segredo: tem que ser "principal"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o código do repositório
      uses: actions/checkout@v4

    - name: Configurando o Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Compilando o Plugin com Maven
      run: mvn -B package --file pom.xml

    - name: Criar o link de download (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: Plugin-KeepInventory
        path: target/*.jar
        
